controller_manager:
  ros__parameters:
    update_rate: 30
    use_sim_time: true

    ack_cont:
      type: ackermann_steering_controller/AckermannSteeringController

    joint_broad:
      type: joint_state_broadcaster/JointStateBroadcaster

ack_cont:
  ros__parameters:


    reference_timeout: 2.0
    front_steering: true
    open_loop: true
    velocity_rolling_window_size: 10
    position_feedback: false
    base_fame_id: base_link
    front_steering: true
    rear_wheels_names: [rear_right_wheel_joint, rear_left_wheel_joint]
    front_wheels_names: [right_steering_joint, left_steering_joint]

    wheelbase: 0.508
    front_wheel_track: 0.4
    rear_wheel_track: 0.4
    front_wheels_radius: 0.08
    rear_wheels_radius: 0.08

    use_stamped_vel: false