twist_mux:
  ros__parameters:
    topics:
        teleop       :
          topic     : cmd_vel
          timeout   : 0.5
          priority  : 90

        joy         :
          topic     : cmd_vel_joy
          timeout   : 0.5
          priority  : 100
        


        braking     :
          topic     : braking_vel
          timeout   : 0.5
          priority  : 120

    locks:
        joy         :
          topic     : brake_lock
          timeout   : 0.5
          priority  : 100
        


